// <auto-generated />
using System;
using LibraryAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryAssessment.Migrations
{
    [DbContext(typeof(AssessmentDbContext))]
    [Migration("20181213015210_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("LibraryAssessment.Models.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Available");

                    b.Property<string>("Title");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryAssessment.Models.Rented", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BookIdId");

                    b.Property<string>("DeleteMe");

                    b.Property<int?>("UsersIdId");

                    b.HasKey("RId");

                    b.HasIndex("BookIdId");

                    b.HasIndex("UsersIdId");

                    b.ToTable("Rented");
                });

            modelBuilder.Entity("LibraryAssessment.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryAssessment.Models.Rented", b =>
                {
                    b.HasOne("LibraryAssessment.Models.Books", "BookId")
                        .WithMany()
                        .HasForeignKey("BookIdId");

                    b.HasOne("LibraryAssessment.Models.Users", "UsersId")
                        .WithMany()
                        .HasForeignKey("UsersIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
